version: "3.9"
services:
  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"